version: '3.7'  # the version of docker-compose
services: 

  dev:
    image: basic_data_science:dev-0.1   # custom-naming the image and specify a tag
    build:
      context: ./proj
      dockerfile: Dockerfile
    ports:
      - 8889:8888
    volumes:
      - ./proj/:/app/
    command: ["jupyter", "notebook", "--ip='*'", "--port=8888", "--no-browser", "--allow-root"]

